import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import { Providers } from "@/app/(main)/providers";
import { SidebarProvider } from "@/components/ui/sidebar";
import { SiteHeader } from "@/app/(main)/components/site-header";
import { BannerContainer } from "@/app/(main)/components/banner";
import { HorizontalMenu } from "@/app/(main)/components/horizontal-menu";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  preload: true
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} ${geistMono.variable}`}>
        <BannerContainer />
        <Providers>
          <SidebarProvider className="flex flex-col">
            <SiteHeader />
            <HorizontalMenu />
            <main className="mt-[var(--banner-height)] flex-1 overflow-y-auto">
              {children}
            </main>
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
