import type { Metadata } from "next";
import "@/styles/globals.css";
import "@/styles/code.css";
import "@/styles/twoslash.css";
import { Providers } from "@/app/providers";
import { AppSidebar } from "@/app/sidebar";
import { SidebarInset, SidebarTrigger } from "@/components/ui/sidebar";
import { Separator } from "@/components/ui/separator";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body>
				<Providers>
					<AppSidebar />
					<SidebarInset>
						<header className="flex h-16 shrink-0 items-center gap-2 border-b px-4">
							<div className="flex flex-1 items-center gap-2 px-3">
								<SidebarTrigger className="-ml-1" />
								<Separator orientation="vertical" className="mr-2 h-4" />
							</div>
						</header>
						<main>{children}</main>
					</SidebarInset>
				</Providers>
			</body>
		</html>
	);
}
